namespace NueGames.NueDeck.Scripts.Enums
{
    public enum AudioActionType
    {
        Attack,
        Pursuit,
        Block,
        Button,
        Draw,
        Drink,
        EnemyDeath,
        Heal,
        Poison,
        Power,
        Swing,
        Slash,
        Guard,
        Shine,
        Flash,
        Rekindle,
        Sweep,
        SwordAndShield1,
        InnerStrength,
        WindUp,
        InfiniteBlade,
        AllIn,
        BulkUp,
        InstantBarrier,
        BarrierCrash,
        StrengthenShield,
        ShieldSiphon1,
        TheBestDefense1,
        Bountiful,
        SaintsPrayer,
        SacredProtection,
        GoddessEmbrace,
        InstantIncantation,
        GodsAngel1,
        SharpDagger,
        MurderGoRound,
        BloodyShank,
        BloodMoney1,
        BloodTracking1,
        ReapersHarvest1,
        RapierStrikes1,
        GainMomentum,
        LeaveNoOpening1,
        EnGarde,
        FollowThrough1,
        FinalGrace1,
        IcicleShot,
        Fireball,
        HailStorm,
        MegaFlare,
        FrozenMirror1,
        BlazingSurge1,
        PerfectHarmony,
        FullyGeared,
        EmergencyDodge,
        NotOutOfOptions,
        SteadyBarricade,
        PreparedPlans,
        TheMastermind,
        Smite,
        AngelDance1,
        GuidingLight,
        PowerToJudge,
        ExecutionVerdict,
        GrandCross1,
        DisarmFoe,
        UnfairPlay,
        LaughAtWeakness,
        OverpoweringDifference,
        ReturnToSender1,
        IllusionOfVictory1,
        NoLight,
        SwordandShield2,
        AllIn2,
        ShieldSiphon2,
        ShieldSiphon3,
        TheBestDefense2,
        GodsAngel2,
        GodsAngel3,
        BloodMoney2,
        BloodMoney3,
        BloodTracking2,
        ReapersHarvest2,
        RapierStrikes2,
        FinalGrace2,
        FollowThrough2,
        LeaveNoOpening2,
        LeaveNoOpening3,
        BlazingSurge2,
        FrozenMirror2,
        AngelDance2,
        AngelDance3,
        GrandCross2,
        IllusionOfVictory2,
        IllusionOfVictory3,
        ReturnToSender2











    }
}