namespace NueGames.NueDeck.Scripts.Enums
{
    public enum CardActionType
    {

        Attack,
        Heal,
        Block,
        IncreaseStrength,
        IncreaseMaxHealth,
        Draw,
        EarnMana,
        LifeSteal,
        Stun,
        Exhaust,
        LightDamage,
        LightManaDraw,
        LightStun,
        BlockDamage,
        BlockMultiply,
        AttackAndBlock,

        Slash,
        Guard,
        Shine,
        Flash,
        Rekindle,
        Sweep,
        SwordAndShield1,
        InnerStrength,
        WindUp,
        InfiniteBlade,
        AllIn,
        BulkUp,
        InstantBarrier,
        BarrierCrash,
        StrengthenShield,
        ShieldSiphon1,
        TheBestDefense,
        Bountiful,
        SaintsPrayer,
        SacredProtection,
        GoddessEmbrace,
        InstantIncantation,
        GodsAngel,
        SharpDagger,
        MurderGoRound,
        BloodyShank,
        BloodMoney,
        BloodTracking,
        ReapersHarvest,
        RapierStrikes,
        GainMomentum,
        LeaveNoOpening,
        EnGarde,
        FollowThrough,
        FinalGrace,
        IcicleShot,
        Fireball,
        HailStorm,
        MegaFlare,
        FrozenMirror,
        BlazingSurge,
        PerfectHarmony,
        FullyGeared,
        EmergencyDodge,
        NotOutOfOptions,
        SteadyBarricade,
        PreparedPlans,
        TheMastermind,
        Smite,
        AngelDance,
        GuidingLight,
        PowerToJudge,
        ExecutionVerdict,
        GrandCross,
        DisarmFoe,
        UnfairPlay,
        LaughAtWeakness,
        OverpoweringDifference,
        ReturnToSender,
        IllusionOfVictory,
        SwordandShield2,
        AllIn2,
        ShieldSiphon2,
        ShieldSiphon3,
        TheBestDefense2,
        GodsAngel2,
        GodsAngel3,
        BloodMoney2,
        BloodMoney3,
        BloodTracking2,
        ReapersHarvest2,
        RapierStrikes2,
        FinalGrace2,
        FollowThrough2,
        LeaveNoOpening2,
        LeaveNoOpening3,
        BlazingSurge2,
        FrozenMirror2,
        AngelDance2,
        AngelDance3,
        GrandCross2,
        IllusionOfVictory2,
        IllusionOfVictory3,
        ReturnToSender2
    










    }
}