namespace NueGames.NueDeck.Scripts.Enums
{
    public enum CardActionType
    {

        Attack,
        Heal,
        Block,
        IncreaseStrength,
        IncreaseMaxHealth,
        Draw,
        EarnMana,
        LifeSteal,
        Stun,
        Exhaust,
        LightDamage,
        LightManaDraw,
        LightStun,
        BlockDamage,
        BlockMultiply,
        AttackAndBlock,
        
    Slash,
    Guard,
    Shine,
    Flash,
    Rekindle,
    Sweep,
    SwordAndShield,
    InnerStrength,
    WindUp,
    InfiniteBlade,
    AllIn,
    BulkUp,
    InstantBarrier,
    BarrierCrash,
    StrengthenShield,
    ShieldSiphon,
    TheBestDefense,
    Bountiful,
    SaintsPrayer,
    SacredProtection,
    GoddessEmbrace,
    InstantIncantation,
    GodsAngel,
    SharpDagger,
    MurderGoRound,
    BloodyShank,
    BloodMoney,
    BloodTracking,
    ReapersHarvest,
    RapierStrikes,
    GainMomentum,
    LeaveNoOpening,
    EnGarde,
    FollowThrough,
    FinalGrace,
    IcicleShot,
    Fireball,
    HailStorm,
    MegaFlare,
    FrozenMirror,
    BlazingSurge,
    PerfectHarmony,
    FullyGeared,
    EmergencyDodge,
    NotOutOfOptions,
    SteadyBarricade,
    PreparedPlans,
    TheMastermind,
    Smite,
    AngelDance,
    GuidingLight,
    PowerToJudge,
    ExecutionVerdict,
    GrandCross,
    DisarmFoe,
    UnfairPlay,
    LaughAtWeakness,
    OverpoweringDifference,
    ReturnToSender,
    IllusionOfVictory








    }
}