namespace NueGames.NueDeck.Scripts.Enums
{ 
    public enum EnemyActionType
    {
        Attack,
        Heal,
        Poison,
        Block,
        Tackle,
        GooSpit,
        Claw,
        Preservation,
        Evolution,
        Pound,
        Regenerate,
        Desperation,
        ApplyDebuff,
        ApplyBuff,
        MultiHitAttack,
        VeilAndVerdict,
        AddCardToDeck,
        SlamDown,
        ScriptRevision,
        Spotlight,
        ApplyBuffCasterFx,
        ApplyDebuffCasterFx,
        ForcedMonologue,
        HarvestWisdom,
        ThoughtLeech,
        SnuffOut,
        HexMark,
        RapidAnalysis
    }
}