namespace NueGames.NueDeck.Scripts.Enums
{
    public enum SpecialKeywords
    {
        Block,
        Strength,
        Poison,
        Exhaust,
        Light,
        Stun,
        Fragile,
        Bleeding,
        Pursuit,
        Ward,
        Cantrip,
        Nephilim,
        Bloodletting,
        Detonate,
        Armor,
        Frostbite,
        Burning,
        Frozen,
        Combustion,
        Fortitude,
        FrozenMirror,
        BlazingSurge,
        PerfectHarmony,
        Commit,
        SteadyBarricade,
        TheMastermind,
        Weakness,
        Judged,
        TheBestDefence,
        Blind,
        Sabotaged,
        Hazy,
        Slimed,
        Temporary,
        Retain,
        Deadstock,
        EndlessChambers,
        FiringLine,
        Vigilance,
        Bastion,
        Reverberation,
        Honor,
        VanguardStance,
        RetainExplanation,
        Desperation,
        Ambush,
        Flying,
        Hidden,
        ManaDrain,
        Burden,
        CloggedCircuits,
        ActorOnStage,
        SeveredString,
        OngoingPerformance,
        GlamouringScenery,
        Might,
        Resilience,
        Spotlight,
        CheatDeath,
        BrushOff,
        Assimilation,
        Amnesia,
        TotalAssimilation,
        Flickering,
        Necrosis,
        Envy,
        Greed,
        SurvivalInstinct,
        Ego,
        Understanding,
        Brittle,
        DamageCut
        






    }
}